baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.amodesthero.com" # the base hostname & protocol for your site, e.g. http://example.com

<header class="masthead">
<h1>Planets of the Universe</h1>
# {% include nav.html navclass='nav-top' %}
</header>